#define _POSIX_C_SOURCE 200809L

#include <signal.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/stat.h>
#include <sys/wait.h>
#include <time.h>
#include <unistd.h>

#include "net.h"

#define TOOL "./build/cweb"

// per-page layout selection, generated by the CLI: every page is wrapped in
// layout.c.html by default, a page that calls cweb_layout_use(req, "admin")
// switches to the layout-admin.c.html shell, and an unknown name falls back to
// the default shell.

static void nap(void)
{
    struct timespec ts = {.tv_sec = 0, .tv_nsec = 20000000};
    nanosleep(&ts, NULL);
}

static int wait_for_port(int port)
{
    for (int i = 0; i < 100; i++) {
        Socket_Handle s = net_connect("127.0.0.1", port);
        if (s != -1) {
            net_close(s);
            return 0;
        }
        nap();
    }
    return -1;
}

static void write_file(const char *path, const char *body)
{
    FILE *f = fopen(path, "w");
    if (f == NULL) {
        perror(path);
        exit(1);
    }
    fputs(body, f);
    fclose(f);
}

static char *request(int port, const char *method, const char *path)
{
    Socket_Handle s = net_connect("127.0.0.1", port);
    if (s == -1) {
        return NULL;
    }
    char req[1024];
    int n = snprintf(req, sizeof req, "%s %s HTTP/1.1\r\n"
                     "Host: 127.0.0.1\r\n"
                     "Connection: close\r\n\r\n",
                     method, path);
    if (net_send_all(s, req, n) != n) {
        net_close(s);
        return NULL;
    }
    size_t cap = 8192, got = 0;
    char *buf = malloc(cap);
    long r;
    while (got < cap - 1 && (r = net_recv(s, buf + got, cap - got - 1)) > 0) {
        got += (size_t)r;
    }
    buf[got] = '\0';
    net_close(s);
    return buf;
}

int main(void)
{
    if (net_init() != 0) {
        return 1;
    }

    char tmp[] = "/tmp/cweb_layout_test_XXXXXX";
    if (mkdtemp(tmp) == NULL) {
        perror("mkdtemp");
        return 1;
    }
    char views[512], partials[512], static_dir[512], out[900], p[600];
    snprintf(views, sizeof views, "%s/views", tmp);
    snprintf(partials, sizeof partials, "%s/views/partials", tmp);
    snprintf(static_dir, sizeof static_dir, "%s/static", tmp);
    snprintf(out, sizeof out, "%s/out", tmp);
    mkdir(views, 0777);
    mkdir(partials, 0777);
    mkdir(static_dir, 0777);

    // default shell carries the partial footer; the admin shell is a distinct
    // document
    snprintf(p, sizeof p, "%s/layout.c.html", views);
    write_file(p,
        "<!DOCTYPE html><html><head><title>SHELL-DEFAULT</title></head><body>"
        "<main><?c cweb_tpl_layout_emit(res); ?></main>"
        "<?c page_footer(req, res, params, user_data); ?>"
        "</body></html>\n");
    snprintf(p, sizeof p, "%s/layout-admin.c.html", views);
    write_file(p,
        "<!DOCTYPE html><html><head><title>SHELL-ADMIN</title></head><body>"
        "<header>admin bar</header><main><?c cweb_tpl_layout_emit(res); ?></main>"
        "</body></html>\n");
    snprintf(p, sizeof p, "%s/index.c.html", views);
    write_file(p, "<p>home body</p>\n");
    snprintf(p, sizeof p, "%s/admin.c.html", views);
    write_file(p, "<?c cweb_layout_use(req, \"layout-admin\"); ?>\n<p>admin body</p>\n");
    snprintf(p, sizeof p, "%s/weird.c.html", views);
    write_file(p, "<?c cweb_layout_use(req, \"no-such-shell\"); ?>\n<p>weird body</p>\n");
    snprintf(p, sizeof p, "%s/404.c.html", views);
    write_file(p, "<p>not found body</p>\n");
    snprintf(p, sizeof p, "%s/partials/footer.c.html", views);
    write_file(p, "<footer>footer-partial</footer>\n");
    snprintf(p, sizeof p, "%s/style.css", static_dir);
    write_file(p, "body{}\n");

    char cmd[2048];
    snprintf(cmd, sizeof cmd, "%s build %s %s . %s >/dev/null", TOOL, views, out, static_dir);
    if (system(cmd) != 0) {
        fprintf(stderr, "cweb build failed for the layout fixture\n");
        return 1;
    }

    Socket_Handle probe = net_listen(0);
    int port = net_bound_port(probe);
    net_close(probe);
    char server[1024];
    snprintf(server, sizeof server, "%s/server", out);

    pid_t child = fork();
    if (child == 0) {
        char portarg[16];
        snprintf(portarg, sizeof portarg, "%d", port);
        execl(server, "server", "--port", portarg, NULL);
        _exit(127);
    }
    if (wait_for_port(port) != 0) {
        fprintf(stderr, "server did not come up on port %d\n", port);
        return 1;
    }

    int ok = 1;
    char *resp;

    resp = request(port, "GET", "/index");
    ok = ok && resp != NULL && strstr(resp, "SHELL-DEFAULT") != NULL &&
         strstr(resp, "home body") != NULL &&
         strstr(resp, "footer-partial") != NULL && strstr(resp, "SHELL-ADMIN") == NULL;
    if (!ok) {
        fprintf(stderr, "a plain page should use the default layout with the footer partial:\n%s\n", resp ? resp : "(connect error)");
    }
    free(resp);

    resp = request(port, "GET", "/admin");
    ok = ok && resp != NULL && strstr(resp, "SHELL-ADMIN") != NULL &&
         strstr(resp, "admin bar") != NULL && strstr(resp, "admin body") != NULL &&
         strstr(resp, "SHELL-DEFAULT") == NULL && strstr(resp, "footer-partial") == NULL;
    if (!ok) {
        fprintf(stderr, "cweb_layout_use should switch the admin page into the admin shell:\n%s\n", resp ? resp : "(connect error)");
    }
    free(resp);

    resp = request(port, "GET", "/weird");
    ok = ok && resp != NULL && strstr(resp, "SHELL-DEFAULT") != NULL &&
         strstr(resp, "weird body") != NULL && strstr(resp, "SHELL-ADMIN") == NULL;
    if (!ok) {
        fprintf(stderr, "an unknown layout name should fall back to the default shell:\n%s\n", resp ? resp : "(connect error)");
    }
    free(resp);

    resp = request(port, "GET", "/missing");
    ok = ok && resp != NULL && strstr(resp, "HTTP/1.1 404") != NULL &&
         strstr(resp, "SHELL-DEFAULT") != NULL && strstr(resp, "not found body") != NULL;
    if (!ok) {
        fprintf(stderr, "the custom 404 should also be framed by the default layout:\n%s\n", resp ? resp : "(connect error)");
    }
    free(resp);

    kill(child, SIGTERM);
    waitpid(child, NULL, 0);
    net_cleanup();
    snprintf(cmd, sizeof cmd, "rm -rf %s", tmp);
    system(cmd);

    if (!ok) {
        return 1;
    }
    printf("layout selection ok\n");
    return 0;
}