#define _POSIX_C_SOURCE 200809L

#include <signal.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/stat.h>
#include <sys/wait.h>
#include <time.h>
#include <unistd.h>

#include "net.h"

#define TOOL "./build/cweb"

// --healthz and --stats, generated by the CLI and exercised over the wire:
// the probe answers a plain-text status line, /healthz is reserved away from
// any page that claims the path, request counts and status buckets move as
// the server is prodded, --routes echoes the knobs, and shutdown prints a
// totals line.

static void nap(void)
{
    struct timespec ts = {.tv_sec = 0, .tv_nsec = 20000000};
    nanosleep(&ts, NULL);
}

static int wait_for_port(int port)
{
    for (int i = 0; i < 100; i++) {
        Socket_Handle s = net_connect("127.0.0.1", port);
        if (s != -1) {
            net_close(s);
            return 0;
        }
        nap();
    }
    return -1;
}

static void write_file(const char *path, const char *body)
{
    FILE *f = fopen(path, "w");
    if (f == NULL) {
        perror(path);
        exit(1);
    }
    fputs(body, f);
    fclose(f);
}

static char *request(int port, const char *method, const char *path,
                     const char *cookie, const char *body)
{
    Socket_Handle s = net_connect("127.0.0.1", port);
    if (s == -1) {
        return NULL;
    }
    char req[2048];
    int n = snprintf(req, sizeof req, "%s %s HTTP/1.1\r\n"
                     "Host: 127.0.0.1\r\n"
                     "Connection: close\r\n",
                     method, path);
    if (cookie != NULL) {
        n += snprintf(req + n, sizeof req - (size_t)n, "Cookie: %s\r\n", cookie);
    }
    if (body != NULL) {
        n += snprintf(req + n, sizeof req - (size_t)n,
                      "Content-Type: application/x-www-form-urlencoded\r\n"
                      "Content-Length: %zu\r\n",
                      strlen(body));
    }
    n += snprintf(req + n, sizeof req - (size_t)n, "\r\n");
    if (body != NULL) {
        memcpy(req + n, body, strlen(body));
        n += (int)strlen(body);
    }
    if (net_send_all(s, req, (long)n) != n) {
        net_close(s);
        return NULL;
    }
    size_t cap = 8192, got = 0;
    char *buf = malloc(cap);
    long r;
    while (got < cap - 1 && (r = net_recv(s, buf + got, cap - got - 1)) > 0) {
        got += (size_t)r;
    }
    buf[got] = '\0';
    net_close(s);
    return buf;
}

// pulls the unsigned that follows "tag " (e.g. "requests ") out of a body
static unsigned long long parse_count(const char *body, const char *tag)
{
    const char *hit = strstr(body, tag);
    if (hit == NULL) {
        return (unsigned long long)-1;
    }
    return strtoull(hit + strlen(tag), NULL, 10);
}

// starts the generated server with the given options (NULLs are skipped).
// when capture is non-NULL the child's stdout is piped back through *out so
// the callers can read the shutdown banner.
static pid_t run_server(const char *server, int port, int healthz,
                        const char *health_path, int stats, FILE **out)
{
    int fds[2] = {-1, -1};
    if (out != NULL && pipe(fds) != 0) {
        perror("pipe");
        exit(1);
    }
    pid_t child = fork();
    if (child == 0) {
        char portarg[16];
        snprintf(portarg, sizeof portarg, "%d", port);
        const char *args[10];
        int i = 0;
        args[i++] = server;
        args[i++] = "--port";
        args[i++] = portarg;
        if (stats) {
            args[i++] = "--stats";
        }
        if (healthz) {
            args[i++] = "--healthz";
        }
        if (health_path != NULL) {
            args[i++] = "--health-path";
            args[i++] = health_path;
        }
        args[i] = NULL;
        if (out != NULL) {
            dup2(fds[1], STDOUT_FILENO);
            close(fds[0]);
            close(fds[1]);
        }
        execvp(server, (char *const *)args);
        _exit(127);
    }
    if (out != NULL) {
        close(fds[1]);
        *out = fdopen(fds[0], "r");
    }
    if (wait_for_port(port) != 0) {
        fprintf(stderr, "server did not come up on port %d\n", port);
        return -1;
    }
    return child;
}

int main(void)
{
    if (net_init() != 0) {
        return 1;
    }

    char tmp[] = "/tmp/cweb_stats_test_XXXXXX";
    if (mkdtemp(tmp) == NULL) {
        perror("mkdtemp");
        return 1;
    }
    char views[512], partials[512], static_dir[512], out[900], p[600];
    snprintf(views, sizeof views, "%s/views", tmp);
    snprintf(partials, sizeof partials, "%s/views/partials", tmp);
    snprintf(static_dir, sizeof static_dir, "%s/static", tmp);
    snprintf(out, sizeof out, "%s/out", tmp);
    mkdir(views, 0777);
    mkdir(partials, 0777);
    mkdir(static_dir, 0777);

    snprintf(p, sizeof p, "%s/index.c.html", views);
    write_file(p, "<p>stats index</p>\n");
    snprintf(p, sizeof p, "%s/probe.c.html", views);
    write_file(p, "<p>PROBE-CONTENT</p>\n");
    snprintf(p, sizeof p, "%s/404.c.html", views);
    write_file(p, "<p>no page</p>\n");
    snprintf(p, sizeof p, "%s/style.css", static_dir);
    write_file(p, "body{}\n");

    char cmd[2048];
    snprintf(cmd, sizeof cmd, "%s build %s %s . %s >/dev/null", TOOL, views, out, static_dir);
    if (system(cmd) != 0) {
        fprintf(stderr, "cweb build failed for the stats fixture\n");
        return 1;
    }

    Socket_Handle probe = net_listen(0);
    int port = net_bound_port(probe);
    net_close(probe);
    char server[1024];
    snprintf(server, sizeof server, "%s/server", out);

    int ok = 1;
    char *resp, banner[4096];
    pid_t child;
    FILE *sout = NULL;

    // a plain server first: the probe.c.html page owns /probe
    child = run_server(server, port, 0, NULL, 0, NULL);
    if (child == -1) {
        return 1;
    }
    resp = request(port, "GET", "/probe", NULL, NULL);
    ok = ok && resp != NULL && strstr(resp, "PROBE-CONTENT") != NULL;
    if (!ok) {
        fprintf(stderr, "without --healthz the page should own /probe:\n%s\n", resp ? resp : "(connect error)");
    }
    free(resp);
    kill(child, SIGTERM);
    waitpid(child, NULL, 0);

    // --healthz --health-path /probe --stats: the probe takes the page's path,
    // reports counters, and the shutdown banner echoes them
    child = run_server(server, port, 1, "/probe", 1, &sout);
    if (child == -1) {
        return 1;
    }

    resp = request(port, "GET", "/probe", NULL, NULL);
    ok = ok && resp != NULL && strstr(resp, "HTTP/1.1 200 OK") != NULL &&
         strstr(resp, "requests") != NULL && strstr(resp, "uptime") != NULL &&
         strstr(resp, "PROBE-CONTENT") == NULL;
    if (!ok) {
        fprintf(stderr, "--healthz --stats should answer with a stats line at the claimed path:\n%s\n", resp ? resp : "(connect error)");
        return 1;
    }
    unsigned long long after1 = parse_count(resp, "requests ");
    free(resp);

    // the default /healthz spot is free again; an unclaimed path 404s there
    resp = request(port, "GET", "/healthz", NULL, NULL);
    ok = ok && resp != NULL && strstr(resp, "HTTP/1.1 404") != NULL;
    if (!ok) {
        fprintf(stderr, "--health-path should move the probe off /healthz:\n%s\n", resp ? resp : "(connect error)");
    }
    free(resp);

    resp = request(port, "GET", "/index", NULL, NULL);
    ok = ok && resp != NULL && strstr(resp, "HTTP/1.1 200 OK") != NULL;
    free(resp);

    resp = request(port, "GET", "/missing", NULL, NULL);
    ok = ok && resp != NULL && strstr(resp, "HTTP/1.1 404") != NULL;
    free(resp);

    resp = request(port, "GET", "/probe", NULL, NULL);
    unsigned long long after2 = parse_count(resp, "requests ");
    unsigned long long fours = parse_count(resp, "4xx ");
    unsigned long long twos = parse_count(resp, "2xx ");
    unsigned long long bytes = parse_count(resp, "bytes ");
    // the stats middleware counts a request only after its handler ran, so a
    // read taken from inside the handler is always one behind; assert growth
    // and the buckets instead of exact totals
    ok = ok && resp != NULL && after1 != (unsigned long long)-1 &&
         after2 > after1 && twos != (unsigned long long)-1 && twos >= 1 &&
         fours != (unsigned long long)-1 && fours >= 1 && bytes > 0;
    if (!ok) {
        fprintf(stderr, "counters should grow and bucket the 404s:\n%s\n", resp ? resp : "(connect error)");
    }
    free(resp);

    kill(child, SIGTERM);
    waitpid(child, NULL, 0);
    size_t bgot = fread(banner, 1, sizeof banner - 1, sout);
    banner[bgot] = '\0';
    fclose(sout);
    // the first probe connection never sent a request, so don't assert counts
    ok = ok && strstr(banner, "cweb: requests") != NULL &&
         strstr(banner, "4xx") != NULL && strstr(banner, "uptime") != NULL;
    if (!ok) {
        fprintf(stderr, "shutdown banner should print the totals line:\n%s\n", banner);
    }

    // --routes lists the knobs without binding; a bad --health-path is rc 2
    {
        char cap[4096];
        snprintf(cmd, sizeof cmd,
                 "'%s' --healthz --health-path /probe --stats --routes < /dev/null 2>&1",
                 server);
        FILE *p = popen(cmd, "r");
        size_t n = 0;
        if (p != NULL) {
            n = fread(cap, 1, sizeof cap - 1, p);
            pclose(p);
        }
        cap[n] = '\0';
        ok = ok && strstr(cap, "healthz: /probe") != NULL &&
             strstr(cap, "stats: on") != NULL;
        if (!ok) {
            fprintf(stderr, "--routes should list the healthz path and the stats knob:\n%s\n", cap);
        }
        snprintf(cmd, sizeof cmd,
                 "'%s' --health-path nope --routes < /dev/null 2>/dev/null; echo $?",
                 server);
        FILE *q = popen(cmd, "r");
        if (q != NULL) {
            n = fread(cap, 1, sizeof cap - 1, q);
            pclose(q);
        }
        cap[n] = '\0';
        ok = ok && cap[0] == '2';
        if (!ok) {
            fprintf(stderr, "--health-path without a leading slash should exit 2:\n%s\n", cap);
        }
    }

    net_cleanup();
    snprintf(cmd, sizeof cmd, "rm -rf %s", tmp);
    system(cmd);

    if (!ok) {
        return 1;
    }
    printf("healthz + stats flags ok\n");
    return 0;
}