/* generated by cweb build; hand edits are overwritten */
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include "http.h"
#include "middleware.h"
#include "net.h"
#include "pages.h"
#include "rate_limit.h"
#include "response.h"
#include "router.h"
#include "security.h"
#include "server.h"
#include "session.h"
#include "static.h"
#include "strmap.h"
#include "template.h"
#include "db.h"
#include "gzip.h"
#include "request_sign.h"
#include "thread.h"
#include "cors.h"
#include "etag.h"
#include "request_id.h"
#include "auth.h"
#include "ip.h"
#include "client_ip.h"
#include "log.h"

// one server-side session store for the whole process, handed to every
// page as user_data; sessions live for an hour of inactivity
static Http_Session_Store cweb_sessions;

// the store behind cweb_database(), opened from --db PATH. zeroed until
// then, so pages that call the accessor before it is open get NULL
static Cweb_Db cweb_database_impl;
static int cweb_database_open = 0;
Cweb_Db *cweb_database(void)
{
    return cweb_database_open ? &cweb_database_impl : NULL;
}

// Cache-Control max-age for the static root, from --static-cache
static unsigned long cweb_static_cache = 0;

// hardening knobs for http_serve_config(), from --max-body,
// --io-timeout and --workers; zero keeps the library defaults
static size_t cweb_max_body = 0;
static unsigned long cweb_io_timeout_ms = 0;
static size_t cweb_workers = 0;

// shared secret for HMAC-signed requests, from --signature-secret;
// NULL keeps request signing off entirely
static const char *cweb_signature_secret = NULL;

// Content-Security-Policy overrides from --csp and --csp-report-only;
// NULL keeps the middleware's built-in default directive
static const char *cweb_csp = NULL;
static const char *cweb_csp_report_only = NULL;

// cross-origin access from --cors; NULL keeps CORS headers off every
// response, "*" opens the API to any origin without credentials
static const char *cweb_cors_origin = NULL;

// --etag stamps strong validators on dynamic responses and answers
// If-None-Match with 304; zero keeps the middleware off
static int cweb_etag = 0;

// --request-id gives every response a unique trace id (and every
// handler a req->request_id); --request-id-inherit additionally
// echoes an inbound X-Request-Id from a trusted proxy
static int cweb_request_id = 0;
static int cweb_request_id_inherit = 0;

// --basic-auth USER:PASS turns the whole app behind HTTP Basic auth
// (401 + WWW-Authenticate for anything without matching credentials);
// the pair is split into these buffers while parsing the flag
static const char *cweb_basic_auth = NULL;
static char cweb_basic_user[256];
static char cweb_basic_pass[256];

// reverse proxies trusted by --trusted-proxy; requests that arrive
// directly from one of these CIDR networks have their X-Forwarded-For
// header believed, so req->client_ip and the rate buckets see the real
// client instead of the proxy's address
static Http_Cidr cweb_trusted[8];
static size_t cweb_trusted_count = 0;

// unix socket listener from --socket PATH; NULL keeps the TCP listener
// as the only way in (a reverse proxy can talk to the app over the
// socket file, no IP stack involved)
static const char *cweb_socket_path = NULL;

// a second http_serve_config() runs in its own thread so the app can
// listen on the TCP port and the unix socket at the same time; both
// stop together when the shutdown signal arrives
typedef struct {
    Socket_Handle listener; // the unix listener this thread serves
    Socket_Handle peer;     // the TCP listener, shut down on stop to wake it
    Http_Handler_Fn handler;
    void *user_data;
    Http_Server_Config cfg;
} Cweb_Listener_Job;

static void cweb_unix_listener(void *arg)
{
    Cweb_Listener_Job *job = arg;
    http_serve_config(job->listener, job->handler, job->user_data, &job->cfg);
    // only one thread handles the shutdown signal, so the peer accept
    // loop may still be asleep; shutdown() wakes it (close() would not
    // reliably), and the loop then sees the shared g_shutdown flag
    net_shutdown(job->peer);
}

// per-route timeout overrides from --route-timeout PATH MS
#define CWEB_MAX_ROUTE_TIMEOUTS 32
static const char *cweb_route_timeout_paths[CWEB_MAX_ROUTE_TIMEOUTS];
static unsigned long cweb_route_timeout_ms[CWEB_MAX_ROUTE_TIMEOUTS];
static int cweb_route_timeout_count = 0;

// parses "8192", "8k", "8K", "2m", "1g" into bytes for
// --max-body; 0 on an empty or non-numeric argument
static size_t cweb_size_arg(const char *s)
{
    char *end = NULL;
    size_t v = strtoul(s, &end, 10);
    if (end == s) {
        return 0;
    }
    switch (*end) {
    case 'k': case 'K': return v * 1024;
    case 'm': case 'M': return v * 1024 * 1024;
    case 'g': case 'G': return v * 1024 * 1024 * 1024;
    default: return v;
    }
}

// the --rate budget's bucket key is identity-aware (see the library's
// http_rate_limit_user_key): requests carrying Basic credentials are
// billed to the account they name — even while the password is still
// being checked, so guessing one account is throttled however many
// caller IPs the attacker spreads across — and everything else is
// billed to the caller's address
static String_View cweb_rate_key(Http_Request *req, void *user_data)
{
    return http_rate_limit_user_key(req, user_data);
}

// disk root for files no page claims, empty when none was configured
static const char cweb_static_root[] = "examples/notes/static";

// every page's handler arrives from the generated pages.h, so any
// page can call any other as a partial

static void list_routes(void)
{
    printf("page_index: /index\n");
    printf("page_index: /\n");
    if (cweb_static_root[0] != '\0') printf("static: /* -> %s\n", cweb_static_root);
    if (cweb_static_cache > 0) printf("static-cache: %lus\n", cweb_static_cache);
    if (cweb_max_body > 0) printf("max-body: %zu bytes\n", cweb_max_body);
    if (cweb_io_timeout_ms > 0) printf("io-timeout: %lums\n", cweb_io_timeout_ms);
    if (cweb_workers > 0) printf("workers: %zu\n", cweb_workers);
    if (cweb_signature_secret != NULL) printf("signature: on\n");
    if (cweb_csp != NULL) printf("csp: %s\n", cweb_csp);
    if (cweb_csp_report_only != NULL) printf("csp-report-only: %s\n", cweb_csp_report_only);
    printf("404: * (fallback)\n");
}

// last resort: let the static root claim first, and when that also
// misses, drop its plain-text answer and render the app's 404 page
static void cweb_fallback(Http_Request *req, Http_Response *res,
                          Str_Map *params, void *user_data)
{
    if (cweb_static_root[0] != '\0') {
        http_serve_static(req, res, (void *)cweb_static_root);
        if (res->status != HTTP_404_NOT_FOUND) {
            return;
        }
        res->status = HTTP_404_NOT_FOUND;
        res->headers.count = 0;
        res->body.count = 0;
    } else {
        http_response_set_status(res, HTTP_404_NOT_FOUND);
    }
    page_404(req, res, params, user_data);
}

static void cweb_wrap_index(Http_Request *req, Http_Response *res,
                          Str_Map *params, void *user_data)
{
    cweb_tpl_capture_begin(res);
    page_index(req, res, params, user_data);
    cweb_tpl_capture_end(res);
    if (cweb_tpl_layout_body().count == 0) {
        return;
    }
    if (res->no_layout) {
        res->body.count = 0;
        http_response_add_body(res, cweb_tpl_layout_body());
        return;
    }
    res->body.count = 0;
    page_layout(req, res, params, user_data);
}

static void cweb_wrap_fallback(Http_Request *req, Http_Response *res,
                               Str_Map *params, void *user_data)
{
    cweb_tpl_capture_begin(res);
    cweb_fallback(req, res, params, user_data);
    cweb_tpl_capture_end(res);
    if (cweb_tpl_layout_body().count == 0) {
        return;
    }
    if (res->no_layout) {
        res->body.count = 0;
        http_response_add_body(res, cweb_tpl_layout_body());
        return;
    }
    res->body.count = 0;
    page_layout(req, res, params, user_data);
}

int main(int argc, char **argv)
{
    int port = 8080;
    int rate_per_min = 0;
    int secure = 0;
    int gzip = 0;
    const char *db_path = NULL;
    const char *log_path = NULL;
    for (int i = 1; i < argc; i++) {
        if (strcmp(argv[i], "--port") == 0 && i + 1 < argc) {
            port = atoi(argv[++i]);
        } else if (strcmp(argv[i], "--rate") == 0 && i + 1 < argc) {
            rate_per_min = atoi(argv[++i]);
        } else if (strcmp(argv[i], "--secure") == 0) {
            secure = 1;
        } else if (strcmp(argv[i], "--gzip") == 0) {
            gzip = 1;
        } else if (strcmp(argv[i], "--db") == 0 && i + 1 < argc) {
            db_path = argv[++i];
        } else if (strcmp(argv[i], "--log") == 0 && i + 1 < argc) {
            log_path = argv[++i];
        } else if (strcmp(argv[i], "--static-cache") == 0 && i + 1 < argc) {
            cweb_static_cache = strtoul(argv[++i], NULL, 10);
        } else if (strcmp(argv[i], "--max-body") == 0 && i + 1 < argc) {
            cweb_max_body = cweb_size_arg(argv[++i]);
        } else if (strcmp(argv[i], "--io-timeout") == 0 && i + 1 < argc) {
            cweb_io_timeout_ms = strtoul(argv[++i], NULL, 10);
        } else if (strcmp(argv[i], "--workers") == 0 && i + 1 < argc) {
            cweb_workers = strtoul(argv[++i], NULL, 10);
        } else if (strcmp(argv[i], "--signature-secret") == 0 && i + 1 < argc) {
            cweb_signature_secret = argv[++i];
        } else if (strcmp(argv[i], "--csp") == 0 && i + 1 < argc) {
            cweb_csp = argv[++i];
        } else if (strcmp(argv[i], "--csp-report-only") == 0 && i + 1 < argc) {
            cweb_csp_report_only = argv[++i];
        } else if (strcmp(argv[i], "--route-timeout") == 0 && i + 2 < argc) {
            if (cweb_route_timeout_count < CWEB_MAX_ROUTE_TIMEOUTS) {
                cweb_route_timeout_paths[cweb_route_timeout_count] = argv[++i];
                cweb_route_timeout_ms[cweb_route_timeout_count] = strtoul(argv[++i], NULL, 10);
                cweb_route_timeout_count++;
            }
        } else if (strcmp(argv[i], "--socket") == 0 && i + 1 < argc) {
            cweb_socket_path = argv[++i];
        } else if (strcmp(argv[i], "--trusted-proxy") == 0 && i + 1 < argc) {
            // comma-separated list of the reverse proxies allowed to
            // stamp X-Forwarded-For; only a request that arrived
            // directly from one of these has its header believed
            const char *spec = argv[++i];
            const char *p = spec;
            for (;;) {
                const char *comma = strchr(p, ',');
                size_t len = comma != NULL ? (size_t)(comma - p)
                                            : strlen(p);
                if (len == 0 || len >= 64) {
                    fprintf(stderr, "cweb: invalid --trusted-proxy %s\n",
                            spec);
                    return 2;
                }
                char buf[64];
                memcpy(buf, p, len);
                buf[len] = '\0';
                if (cweb_trusted_count >= 8 ||
                    http_cidr_parse(&cweb_trusted[cweb_trusted_count],
                                    buf) != 0) {
                    fprintf(stderr, "cweb: invalid --trusted-proxy %s\n",
                            spec);
                    return 2;
                }
                cweb_trusted_count++;
                if (comma == NULL) {
                    break;
                }
                p = comma + 1;
            }
        } else if (strcmp(argv[i], "--cors") == 0 && i + 1 < argc) {
            cweb_cors_origin = argv[++i];
        } else if (strcmp(argv[i], "--etag") == 0) {
            cweb_etag = 1;
        } else if (strcmp(argv[i], "--request-id") == 0) {
            cweb_request_id = 1;
        } else if (strcmp(argv[i], "--request-id-inherit") == 0) {
            // honoring an inbound id implies the middleware is on
            cweb_request_id = 1;
            cweb_request_id_inherit = 1;
        } else if (strcmp(argv[i], "--basic-auth") == 0 && i + 1 < argc) {
            // split USER:PASS at its first ':', keep the whole
            // password (which may itself contain colons)
            const char *spec = argv[++i];
            const char *colon = strchr(spec, ':');
            if (colon != NULL) {
                size_t n = (size_t)(colon - spec);
                if (n >= sizeof cweb_basic_user) {
                    n = sizeof cweb_basic_user - 1;
                }
                memcpy(cweb_basic_user, spec, n);
                cweb_basic_user[n] = '\0';
                snprintf(cweb_basic_pass, sizeof cweb_basic_pass,
                         "%s", colon + 1);
            } else {
                snprintf(cweb_basic_user, sizeof cweb_basic_user,
                         "%s", spec);
                cweb_basic_pass[0] = '\0';
            }
            cweb_basic_auth = cweb_basic_user;
        } else if (strcmp(argv[i], "--routes") == 0) {
            list_routes();
            return 0;
        } else {
            fprintf(stderr, "cweb: unknown option %s\n", argv[i]);
            return 2;
        }
    }
    if (db_path != NULL) {
        if (cweb_db_open(&cweb_database_impl, db_path) != 0) {
            fprintf(stderr, "cweb: cannot open db %s\n", db_path);
            return 1;
        }
        cweb_database_open = 1;
    }
    if (net_init() != 0) {
        fprintf(stderr, "cweb: net_init failed\n");
        return 1;
    }
    Http_Router r;
    router_init(&r);
    http_session_store_init(&cweb_sessions, 3600);
    // with --db the session store persists to it, so logins survive
    // a restart as long as the same database file is passed again
    if (cweb_database_open) {
        http_session_store_set_db(&cweb_sessions, &cweb_database_impl);
    }
    router_add(&r, HTTP_GET, "/index", cweb_wrap_index, &cweb_sessions);
    router_add(&r, HTTP_POST, "/index", cweb_wrap_index, &cweb_sessions);
    router_add(&r, HTTP_GET, "/", cweb_wrap_index, &cweb_sessions);
    router_add(&r, HTTP_POST, "/", cweb_wrap_index, &cweb_sessions);
    router_add(&r, HTTP_GET, "*", cweb_wrap_fallback, &cweb_sessions);
    router_add(&r, HTTP_POST, "*", cweb_wrap_fallback, &cweb_sessions);
    if (cweb_static_cache > 0) {
        http_static_set_cache(cweb_static_cache);
    }
    // apply per-route timeout overrides
    for (int i = 0; i < cweb_route_timeout_count; i++) {
        if (router_set_timeout(&r, HTTP_GET, cweb_route_timeout_paths[i], cweb_route_timeout_ms[i]) == 0)
            router_set_timeout(&r, HTTP_POST, cweb_route_timeout_paths[i], cweb_route_timeout_ms[i]);
    }

    printf("cweb server on http://0.0.0.0:%d\n", port);
    Socket_Handle listener = net_listen(port);
    if (listener < 0) {
        fprintf(stderr, "cweb: listen %d: %s\n", port,
                net_error_string());
        return 1;
    }
    Socket_Handle unix_listener = -1;
    if (cweb_socket_path != NULL) {
        // --socket is served alongside the TCP port, so a reverse
        // proxy can reach the app over a local socket file
        unix_listener = net_listen_unix(cweb_socket_path);
        if (unix_listener < 0) {
            fprintf(stderr, "cweb: unix listen %s: %s\n",
                    cweb_socket_path, net_error_string());
            net_close(listener);
            return 1;
        }
        printf("cweb server on unix:%s\n", cweb_socket_path);
    }
    FILE *clf_file = NULL;
    if (log_path != NULL) {
        // --log appends Common Log Format access lines for every
        // completed request; opened here so a failure is loud
        clf_file = fopen(log_path, "a");
        if (clf_file == NULL) {
            fprintf(stderr, "cweb: cannot open access log %s\n", log_path);
            return 1;
        }
        log_set_clf(clf_file);
    }
    Http_Server_Config cfg = {0};
    cfg.max_body = cweb_max_body;
    cfg.io_timeout_ms = cweb_io_timeout_ms;
    cfg.workers = cweb_workers;

    // the dispatch and its state are shared by every listener
    Http_Handler_Fn cweb_dispatch;
    void *cweb_user;
    Http_RateLimiter limiter;
    int cweb_middleware = secure || gzip || rate_per_min > 0 ||
                         cweb_signature_secret != NULL ||
                         cweb_basic_auth != NULL ||
                         cweb_cors_origin != NULL ||
                         cweb_etag || cweb_request_id ||
                         cweb_csp != NULL || cweb_csp_report_only != NULL;
    void *cweb_chain_data = NULL;
    if (cweb_middleware) {
        // hardening headers, (optionally) a per-client request
        // budget, gzip wrapping, a shared-secret signature, and a
        // Content-Security-Policy run around every response
        if (rate_per_min > 0) {
            // N requests a minute per bucket: the bucket starts full
            // so a momentary burst of N passes, beyond that the caller
            // is answered with 429 until the bucket refills. buckets
            // belong to who the request claims to be (see the
            // identity-aware key above), falling back to the address
            http_rate_limiter_init(&limiter, (double)rate_per_min / 60.0,
                                   (double)rate_per_min);
            limiter.key_fn = cweb_rate_key;
        }
        Http_Signature_Options sig_opts = {0};
        if (cweb_signature_secret != NULL) {
            // --signature-secret makes every request prove it came
            // from a proxy holding the same secret, 403 otherwise
            sig_opts.secret = cweb_signature_secret;
        }
        // --csp overrides the middleware's default directive;
        // --csp-report-only adds a monitoring-only policy on top
        Http_Security_Options sec_opts = {0};
        if (cweb_csp != NULL || cweb_csp_report_only != NULL) {
            sec_opts.csp = cweb_csp;
            sec_opts.csp_report_only = cweb_csp_report_only;
        }
        Http_Cors_Options cors_opts = {0};
        if (cweb_cors_origin != NULL) {
            cors_opts.origin = cweb_cors_origin;
        }
        Http_Middleware_Chain chain;
        http_middleware_init(&chain);
        Http_ClientIp_Options ip_opts = {cweb_trusted, cweb_trusted_count};
        if (cweb_trusted_count > 0) {
            // resolves req->client_ip from X-Forwarded-For for requests
            // that arrived straight from a trusted proxy. outermost, so
            // access logs and the per-address rate buckets below name
            // the real client, never the proxy
            http_middleware_add(&chain, http_client_ip_middleware,
                                &ip_opts);
        }
        if (cweb_request_id) {
            // --request-id stamps every response (and every
            // req->request_id) with a unique trace id; outermost,
            // so even a short-circuited chain still carries it on
            Http_RequestId_Opts rid_opts = {0};
            rid_opts.honor_incoming = cweb_request_id_inherit;
            http_middleware_add(&chain, http_request_id_middleware,
                                &rid_opts);
        }
        if (secure || cweb_csp != NULL || cweb_csp_report_only != NULL) {
            http_middleware_add(&chain, http_security_middleware,
                                (cweb_csp != NULL || cweb_csp_report_only != NULL)
                                    ? &sec_opts : NULL);
        }
        if (cweb_signature_secret != NULL) {
            http_middleware_add(&chain, http_signature_middleware,
                                &sig_opts);
        }
        if (rate_per_min > 0) {
            // the budget sits outside the Basic-auth guard on purpose:
            // the identity-aware key bills authenticated requests to
            // the account they name, so a brute-forced password or a
            // burst from one caller gets 429 before the guard can even
            // answer 401, instead of rerolling the bucket on every try
            http_middleware_add(&chain, http_rate_limit_middleware,
                                &limiter);
        }
        Http_BasicAuth_Options basic_opts = {0};
        if (cweb_basic_auth != NULL) {
            // --basic-auth USER:PASS locks the whole app behind HTTP
            // Basic auth; the pair was split into these buffers while
            // parsing the flag, and anything without matching
            // credentials is answered 401 + WWW-Authenticate
            basic_opts.user = cweb_basic_user;
            basic_opts.pass = cweb_basic_pass;
            http_middleware_add(&chain, http_basic_auth_middleware,
                                &basic_opts);
        }
        if (gzip) {
            // --gzip compresses compressible bodies on the way out
            http_middleware_add(&chain, http_gzip_middleware, NULL);
        }
        if (cweb_etag) {
            // --etag hashes the uncompressed body for a stable
            // validator regardless of Content-Encoding; gzip runs
            // outermost so it still compresses the final bytes
            http_middleware_add(&chain, http_etag_middleware, NULL);
        }
        if (cweb_cors_origin != NULL) {
            // --cors answers browser preflights and stamps
            // Access-Control-Allow-Origin on every matching request
            http_middleware_add(&chain, http_cors_middleware,
                                &cors_opts);
        }
        cweb_dispatch = http_middleware_build(&chain, router_dispatch,
                                              &r, &cweb_chain_data);
        http_middleware_free(&chain);
        cweb_user = cweb_chain_data;
    } else {
        cweb_dispatch = router_dispatch;
        cweb_user = &r;
    }

    int rc;
    if (unix_listener >= 0) {
        // the unix listener accepts in its own thread while the main
        // thread keeps the TCP accept loop; both stop on the same
        // shutdown signal and drain their in-flight requests together
        Cweb_Listener_Job job = {unix_listener, listener, cweb_dispatch,
                                cweb_user, cfg};
        Thread unix_thread;
        if (thread_init(&unix_thread, cweb_unix_listener, &job) != 0) {
            fprintf(stderr, "cweb: cannot start the unix listener\n");
            net_close(listener);
            net_close(unix_listener);
            net_unix_unlink(cweb_socket_path);
            return 1;
        }
        rc = http_serve_config(listener, cweb_dispatch, cweb_user, &cfg);
        net_shutdown(unix_listener); // wake the peer loop if it is asleep
        thread_join(&unix_thread);
        net_close(unix_listener);
        net_close(listener);
        net_unix_unlink(cweb_socket_path);
    } else {
        rc = http_serve_config(listener, cweb_dispatch, cweb_user, &cfg);
    }
    if (cweb_middleware) {
        http_middleware_data_free(cweb_chain_data);
        if (rate_per_min > 0) {
            http_rate_limiter_free(&limiter);
        }
    }
    http_session_store_dump(&cweb_sessions);
    http_session_store_free(&cweb_sessions);
    if (clf_file != NULL) {
        log_set_clf(NULL);
        fclose(clf_file);
    }
    router_free(&r);
    net_cleanup();
    if (cweb_database_open) {
        cweb_db_close(&cweb_database_impl);
    }
    return rc;
}
