/* generated by cweb build; hand edits are overwritten */
#ifndef CWEB_PAGES_H
#define CWEB_PAGES_H

#include "request.h"
#include "response.h"
#include "strmap.h"
#include "db.h"

/* one declaration per page. call another page as a partial from
 * any view: <?c page_x(req, res, params, user_data); ?> */
void page_404(Http_Request *req, Http_Response *res,
      Str_Map *params, void *user_data);
void page_index(Http_Request *req, Http_Response *res,
      Str_Map *params, void *user_data);
void page_layout(Http_Request *req, Http_Response *res,
      Str_Map *params, void *user_data);
void page_footer(Http_Request *req, Http_Response *res,
      Str_Map *params, void *user_data);

/* the store opened from the server's --db PATH, or NULL when the
 * server ran without one. every page shares the same Cweb_Db, so
 * <?c Cweb_Db *db = cweb_database(); ?> reads and writes persist
 * between requests. check for NULL before touching it. */
Cweb_Db *cweb_database(void);
#endif
