// generated from RFC 7541 Appendix A (Static Table); do not hand-edit

#include "sv.h"

#define SV_C(s) (String_View){ (s), sizeof(s) - 1 }

typedef struct { String_View name; String_View value; } Hpack_Static_Entry;
static const Hpack_Static_Entry HPACK_STATIC_TABLE[61] = {
    { SV_C(":authority"), { NULL, 0 } },
    { SV_C(":method"), SV_C("GET") },
    { SV_C(":method"), SV_C("POST") },
    { SV_C(":path"), SV_C("/") },
    { SV_C(":path"), SV_C("/index.html") },
    { SV_C(":scheme"), SV_C("http") },
    { SV_C(":scheme"), SV_C("https") },
    { SV_C(":status"), SV_C("200") },
    { SV_C(":status"), SV_C("204") },
    { SV_C(":status"), SV_C("206") },
    { SV_C(":status"), SV_C("304") },
    { SV_C(":status"), SV_C("400") },
    { SV_C(":status"), SV_C("404") },
    { SV_C(":status"), SV_C("500") },
    { SV_C("accept-charset"), { NULL, 0 } },
    { SV_C("accept-encoding"), SV_C("gzip, deflate") },
    { SV_C("accept-language"), { NULL, 0 } },
    { SV_C("accept-ranges"), { NULL, 0 } },
    { SV_C("accept"), { NULL, 0 } },
    { SV_C("access-control-allow-origin"), { NULL, 0 } },
    { SV_C("age"), { NULL, 0 } },
    { SV_C("allow"), { NULL, 0 } },
    { SV_C("authorization"), { NULL, 0 } },
    { SV_C("cache-control"), { NULL, 0 } },
    { SV_C("content-disposition"), { NULL, 0 } },
    { SV_C("content-encoding"), { NULL, 0 } },
    { SV_C("content-language"), { NULL, 0 } },
    { SV_C("content-length"), { NULL, 0 } },
    { SV_C("content-location"), { NULL, 0 } },
    { SV_C("content-range"), { NULL, 0 } },
    { SV_C("content-type"), { NULL, 0 } },
    { SV_C("cookie"), { NULL, 0 } },
    { SV_C("date"), { NULL, 0 } },
    { SV_C("etag"), { NULL, 0 } },
    { SV_C("expect"), { NULL, 0 } },
    { SV_C("expires"), { NULL, 0 } },
    { SV_C("from"), { NULL, 0 } },
    { SV_C("host"), { NULL, 0 } },
    { SV_C("if-match"), { NULL, 0 } },
    { SV_C("if-modified-since"), { NULL, 0 } },
    { SV_C("if-none-match"), { NULL, 0 } },
    { SV_C("if-range"), { NULL, 0 } },
    { SV_C("if-unmodified-since"), { NULL, 0 } },
    { SV_C("last-modified"), { NULL, 0 } },
    { SV_C("link"), { NULL, 0 } },
    { SV_C("location"), { NULL, 0 } },
    { SV_C("max-forwards"), { NULL, 0 } },
    { SV_C("proxy-authenticate"), { NULL, 0 } },
    { SV_C("proxy-authorization"), { NULL, 0 } },
    { SV_C("range"), { NULL, 0 } },
    { SV_C("referer"), { NULL, 0 } },
    { SV_C("refresh"), { NULL, 0 } },
    { SV_C("retry-after"), { NULL, 0 } },
    { SV_C("server"), { NULL, 0 } },
    { SV_C("set-cookie"), { NULL, 0 } },
    { SV_C("strict-transport-security"), { NULL, 0 } },
    { SV_C("transfer-encoding"), { NULL, 0 } },
    { SV_C("user-agent"), { NULL, 0 } },
    { SV_C("vary"), { NULL, 0 } },
    { SV_C("via"), { NULL, 0 } },
    { SV_C("www-authenticate"), { NULL, 0 } },
};
