#ifndef CWEB_TEMPLATE_H
#define CWEB_TEMPLATE_H

#include <time.h>

#include "response.h"
#include "strbuf.h"
#include "sv.h"

// The .c.html compiler: takes a page written as HTML with C spliced in and
// emits C source for a route handler
//
//   static void <fn_name>(Http_Request *req, Http_Response *res,
//                         Str_Map *params, void *user_data)
//
// so the output drops straight into router_add. Everything outside the code
// tags is emitted verbatim into the response body. three forms are supported:
//
//   <?c ... ?>   raw C statements, executed as-is. req, res, params and
//                user_data are in scope, as are stdio/stdlib/string/stdint.
//   <?c= expr ?> appends expr to the body as-is; expr must be a const char*.
//   <?h= expr ?> appends html_escape_into(res->body, expr); expr is a
//                String_View, e.g. sv_from_cstr(user_name).
//
// the generated handler sets Content-Type text/html before any of the above.
// returns 0 with the C source appended to out, or -1 with a message in *err
// (may be NULL) when the template is malformed.
int cweb_template_to_c(String_View source, const char *fn_name,
                       Strbuf *out, Strbuf *err);

// like cweb_template_to_c but reads the page from disk and derives the fn
// name from the basename: "views/MyPage.c.html" becomes page_MyPage.
int cweb_template_compile(const char *path, Strbuf *out, Strbuf *err);

// ---------------------------------------------------------------------------
// layout capture
// ---------------------------------------------------------------------------
// a views/layout.c.html wraps every routed page. the page handler renders
// into a per-thread capture instead of the response, then the layout runs and
// redraws the body with that markup in the middle. every cweb_tpl_out /
// cweb_tpl_escape a generated page emits funnels through cweb_tpl_add, which
// honors the active capture, so partials rendered from inside a page land in
// the capture too.

// appends to the response body, or to the capturing thread's buffer while a
// capture is active. emitted code's only primitive, so both normal and
// escaping output flows are captured transparently.
void cweb_tpl_add(Http_Response *res, const void *data, size_t len);

// opens a capture on this thread: subsequent cweb_tpl_add writes are held
// back from the response. reusable; the previous capture is discarded.
void cweb_tpl_capture_begin(void);

// closes the capture; the held-back bytes are free for the layout to read and
// the thread returns to writing straight into responses.
void cweb_tpl_capture_end(void);

// the markup captured by the most recent cweb_tpl_capture_begin/end span on
// this thread. valid until the next begin. layouts splice it in with
//   <?c cweb_tpl_layout_emit(res); ?>
String_View cweb_tpl_layout_body(void);

// writes the current capture into res, as layouts do to drop the wrapped
// page body into the middle of the document shell.
void cweb_tpl_layout_emit(Http_Response *res);

// the name cweb_template_compile would derive for a path, kept in its own
// helper so tools (the CLI, autogenerated mains) can agree with the library
// without reimplementing the slugging. buf needs at least 104 bytes.
void cweb_template_page_name(const char *path, char *out, size_t out_size);

// ---------------------------------------------------------------------------
// date and time formatting helpers
// ---------------------------------------------------------------------------
// pages turn timestamps into readable text with these; the output is plain
// text with no markup, so it is appended raw (like cweb_tpl_out, not the
// escaping <?h= form):
//
//   <?c cweb_tpl_date_local(res, last_seen); ?>
//
// local-time helpers defer to the C library's strftime() with whatever tz the
// process runs under.
void cweb_tpl_date(Http_Response *res, time_t t);        // RFC 7231, GMT
void cweb_tpl_date_local(Http_Response *res, time_t t);  // "1970-01-01 00:00:00"
void cweb_tpl_strftime(Http_Response *res, const char *fmt, time_t t);
void cweb_tpl_now(Http_Response *res);                   // local now stamp

#endif